### ISSUE TITLE
log_sigma

### ISSUE THREAD

**Issue by nationalflag** [vdumoulin/discgen#4]
I wanna ask why you set log_sigma to be zero rather than learn it through the net? 
And you set mu_theta to be the reconstructed or sampled image directly, why don't you sample from the gaussian distribution with mu_theta and log_sigma?

**Comment by alexmlamb** [comment]
"And you set mu_theta to be the reconstructed or sampled image directly,
why don't you sample from the gaussian distribution with mu_theta and
log_sigma?"

This is pretty common with variational autoencoders.  Usually p(x | z) is
something simple like a gaussian with independent dimensions, which doesn't
fit the noise that actually occurs in images (lots of local spatial
correlation).  So sampling from the gaussian distribution would be
equivalent to injecting salt and pepper noise.

Best,

Alex.

**Comment by vdumoulin** [comment]
The log sigma parameters are initialized to zero, but they are learned as well. They're just not a function of z. The reason for that is to avoid numerical instabilities.

**Comment by CallerGranet** [comment]
@vdumoulin I don't understand when are the log_sigma's parameters learned...
They are added to the parameter list for GradientDescent, but, shouldn't the log_sigma values be fixed during training of vae? Am I missing something?

**Comment by vdumoulin** [comment]
@CallerGranet they are trained jointly with the rest of the model parameters. There's no prescribed way of parametrizing `p(x | z)` in VAEs; any specific architectural choice simply reflects a different class of conditional densities being considered. In our case, we consider the family of factorized Gaussian conditional densities whose means are a function of the latent code `z` and whose variances  are independent of the latent code `z`.

Hope that helps!
